export const activity = [
  { icon: 'wallet-outline', color: '#22C55E', title: 'Payment received', meta: 'Today, 8:45 AM', value: '$89.00' },
  { icon: 'star', color: '#FFC107', title: 'New 5-star review', meta: 'Great service! Very professional.', value: '5.0' },
  { icon: 'checkmark-done', color: '#2F80FF', title: 'Job completed', meta: 'Battery Replacement - Job #12341', value: '$125.00' },
];

export const schedule = [
  { time: '10:30 AM', title: 'Battery Jump', vehicle: 'Toyota Camry', eta: 'In 15 min' },
  { time: '12:15 PM', title: 'Tire Change', vehicle: 'Honda Accord', eta: 'In 2h' },
  { time: '2:00 PM', title: 'Diagnostics', vehicle: 'BMW X5', eta: 'In 3h 45m' },
];

export const demoRequests = [
  {
    id: 'demo-request-1',
    demo: true,
    accent: '#42D463',
    icon: 'battery-charging-outline',
    service: {
      issueName: 'Battery Jump',
      serviceType: 'jump_start',
      diagnosticInfo: {
        intakeAnswers: { interior_lights: 'No', engine_clicks: 'Yes', battery_age: 'No' },
        intakeQuestions: [
          { key: 'interior_lights', label: 'Are the interior lights working?' },
          { key: 'engine_clicks', label: 'Does the engine click when starting?' },
          { key: 'battery_age', label: 'Is the battery older than 3 years?' },
        ],
      },
    },
    vehicle: { make: 'Toyota Highlander', year: '2018' },
    pickup: { address: '123 Main St, San Francisco, CA' },
    payment: { totalHeld: 89 },
    eta: 'ETA 15 min',
    distance: '5.2 mi away',
  },
  {
    id: 'demo-request-2',
    demo: true,
    accent: '#FF9F1A',
    icon: 'car-sport-outline',
    service: {
      issueName: 'Towing',
      serviceType: 'towing',
      diagnosticInfo: {
        intakeAnswers: { vehicle_undrivable: 'Yes', road_type: 'No', injury: 'No', keys_available: 'Yes' },
        intakeQuestions: [
          { key: 'vehicle_undrivable', label: 'Is the vehicle completely undrivable?' },
          { key: 'road_type', label: 'Are you on a highway?' },
          { key: 'injury', label: 'Is anyone injured?' },
          { key: 'keys_available', label: 'Are the keys available?' },
        ],
      },
    },
    vehicle: { make: 'Honda Civic', year: '2020' },
    pickup: { address: '456 Oak Ave, San Francisco, CA' },
    dropoff: { address: '789 Pine St, San Francisco, CA 94108' },
    payment: { totalHeld: 120 },
    eta: 'ETA 20 min',
    distance: '6.8 mi away',
  },
  {
    id: 'demo-request-3',
    demo: true,
    accent: '#A855F7',
    icon: 'construct-outline',
    service: {
      issueName: 'Tire Change',
      serviceType: 'tire_change',
      diagnosticInfo: {
        intakeAnswers: { vehicle_moves: 'No', spare_tire: 'Yes' },
        intakeQuestions: [
          { key: 'vehicle_moves', label: 'Can the vehicle still move?' },
          { key: 'spare_tire', label: 'Do you have a spare tire?' },
        ],
      },
    },
    vehicle: { make: 'Nissan Altima', year: '2019' },
    pickup: { address: '789 Pine St, San Francisco, CA' },
    payment: { totalHeld: 69 },
    eta: 'ETA 12 min',
    distance: '3.1 mi away',
  },
  {
    id: 'demo-request-4',
    demo: true,
    accent: '#2F80FF',
    icon: 'speedometer-outline',
    service: {
      issueName: 'Diagnostics',
      serviceType: 'mobile_mechanic',
      diagnosticInfo: {
        intakeAnswers: { drivable: 'Yes', safe_location: 'Yes', immediate_help: 'No' },
        intakeQuestions: [
          { key: 'drivable', label: 'Is the vehicle drivable?' },
          { key: 'safe_location', label: 'Are you in a safe location?' },
          { key: 'immediate_help', label: 'Do you need immediate help?' },
        ],
      },
    },
    vehicle: { make: 'BMW X5', year: '2017' },
    pickup: { address: '321 Elm St, San Francisco, CA' },
    payment: { totalHeld: 95 },
    eta: 'ETA 18 min',
    distance: '4.5 mi away',
  },
];

export const demoJobs = [
  {
    id: 'job-12345',
    number: '12345',
    status: 'on_the_way',
    eta: '10:24 AM',
    accent: '#42D463',
    icon: 'battery-charging-outline',
    customer: { name: 'John Smith', initials: 'JS', phone: '(415) 555-0198' },
    service: { type: 'Battery Jump', icon: 'battery-charging-outline' },
    vehicle: { make: 'Toyota Highlander', year: '2018', color: 'White' },
    pickup: { address: '123 Main St, San Francisco, CA' },
    payment: { method: 'VISA', last4: '4242', total: 89 },
    customerNote: "Car won't start, lights are dim.",
    orderContext: {
      customerComplaints: [
        { id: 'no-start', label: "Vehicle won't start", value: 'Customer says the engine does not crank.' },
        { id: 'dim-lights', label: 'Dim dashboard lights', value: 'Lights became weak after several attempts.' },
        { id: 'battery-warning', label: 'Battery warning', value: 'Battery icon appeared before the vehicle stopped.' },
      ],
    },
    createdAt: 'Today, 9:15 AM',
  },
  {
    id: 'job-12346',
    number: '12346',
    status: 'arrived',
    eta: '12:30 PM',
    accent: '#FF9F1A',
    icon: 'car-sport-outline',
    customer: { name: 'Maria Garcia', initials: 'MG', phone: '(415) 555-0234' },
    service: { type: 'Towing', icon: 'car-sport-outline' },
    vehicle: { make: 'Honda Civic', year: '2020', color: 'Blue' },
    pickup: { address: '456 Oak Ave, San Francisco, CA' },
    dropoff: { address: '789 Pine St, San Francisco, CA 94108' },
    payment: { method: 'VISA', last4: '1234', total: 120 },
    customerNote: 'Car broke down on the highway.',
    createdAt: 'Today, 11:50 AM',
  },
  {
    id: 'job-12347',
    number: '12347',
    status: 'waiting_approval',
    eta: '12 min',
    accent: '#EAB308',
    icon: 'battery-charging-outline',
    customer: { name: 'David Lee', initials: 'DL', phone: '(415) 555-0312' },
    service: { type: 'Battery Replacement', icon: 'battery-charging-outline' },
    vehicle: { make: 'BMW X5', year: '2017', color: 'Black' },
    pickup: { address: '789 Pine St, San Francisco, CA' },
    payment: { method: 'Mastercard', last4: '5678', total: 180 },
    customerNote: 'Customer reviewing your estimate.',
    createdAt: 'Today, 1:30 PM',
  },
];

export const scheduledJobs = [
  {
    id: 'scheduled-1',
    number: '23001',
    status: 'scheduled',
    eta: 'In 2h 15m',
    time: '2:30 PM',
    accent: '#2F80FF',
    icon: 'calendar-outline',
    customer: { name: 'Rosa Carter', initials: 'RC', phone: '(415) 555-0147' },
    service: { type: 'Tire Change', icon: 'calendar-outline' },
    vehicle: { make: 'Nissan Altima', year: '2019', color: 'Gray' },
    pickup: { address: '321 Market St, San Francisco, CA' },
    payment: { method: 'VISA', last4: '8842', total: 69 },
    customerNote: 'Scheduled roadside tire change.',
    createdAt: 'Today, 2:30 PM',
  },
  {
    id: 'scheduled-2',
    number: '23002',
    status: 'scheduled',
    eta: 'Tomorrow',
    time: '9:00 AM',
    accent: '#2F80FF',
    icon: 'calendar-outline',
    customer: { name: 'Evan Brooks', initials: 'EB', phone: '(415) 555-0183' },
    service: { type: 'Diagnostics', icon: 'calendar-outline' },
    vehicle: { make: 'Ford Escape', year: '2021', color: 'Blue' },
    pickup: { address: '88 Mission St, San Francisco, CA' },
    payment: { method: 'VISA', last4: '3920', total: 95 },
    customerNote: 'Scheduled diagnostic appointment.',
    createdAt: 'Tomorrow, 9:00 AM',
  },
];
